name: Fork OSS

on:  
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Git-version
      run: git version   
    env:
      CI: true
      repository: "https://github.com/kubernetes-sigs/kubespray.git"
