name: Fork OSS

on:  
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'master'
    - run: |
        git clone https://github.com/kubernetes-sigs/kubespray.git"    
    env:
      CI: true
      repository: "https://github.com/kubernetes-sigs/kubespray.git"
