name: Fork OSS

on:  
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      with:
        repository: kubernetes-sigs/kubespray.git
    
    env:
      CI: true
      repository: "https://github.com/kubernetes-sigs/kubespray.git"
